[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "web-crawler-py"
version = "0.1.0"
description = "A web crawler written in Python"
requires-python = ">=3.12"

dependencies = [
    "inject>=5.3.0",
    "loguru>=0.7.3",
    "pydantic>=2.12.3",
    "python-dotenv>=1.2.1"
]

[project.optional-dependencies]
test = [
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "pytest-cov>=7.0.0"
]

[project.scripts]
crawl = "src.main:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]